// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'endpoint.dart';
import 'key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_item`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartAddressLookup`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `resolve`

/// Binds an endpoint that uses a **Dart-implemented** address lookup (only): the n0 default DNS/pkarr
/// lookup is cleared and replaced by `resolve`, so `connect`ing to a peer known only by its
/// `EndpointId` calls back into Dart to discover its addresses. Otherwise identical to
/// `endpoint_bind`.
Future<Endpoint> endpointBindWithAddressLookup({
  Uint8List? secretKey,
  required List<Uint8List> alpns,
  required int relayModeKind,
  required List<String> customRelayUrls,
  required FutureOr<EndpointAddrParts?> Function(Uint8List) resolve,
}) => RustLib.instance.api.crateApiAddressLookupEndpointBindWithAddressLookup(
  secretKey: secretKey,
  alpns: alpns,
  relayModeKind: relayModeKind,
  customRelayUrls: customRelayUrls,
  resolve: resolve,
);
