// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_endpoint_addr`, `parts_from_endpoint_addr`, `to_arr32`, `to_arr64`

/// Generates a fresh random secret key, returning its 32 raw bytes.
Uint8List secretKeyGenerate() => RustLib.instance.api.crateApiKeySecretKeyGenerate();

/// Derives the 32-byte public key (EndpointId) from a 32-byte secret key.
Uint8List secretKeyPublic({required List<int> secret}) =>
    RustLib.instance.api.crateApiKeySecretKeyPublic(secret: secret);

/// Signs `msg` with the secret key, returning a 64-byte ed25519 signature.
Uint8List secretKeySign({required List<int> secret, required List<int> msg}) =>
    RustLib.instance.api.crateApiKeySecretKeySign(secret: secret, msg: msg);

/// Validates that 32 bytes form a valid ed25519 public key (curve point). Errors otherwise.
void publicKeyCheck({required List<int> public}) =>
    RustLib.instance.api.crateApiKeyPublicKeyCheck(public: public);

/// Returns `true` iff `signature` is a valid signature of `msg` under `public`.
bool publicKeyVerify({
  required List<int> public,
  required List<int> msg,
  required List<int> signature,
}) =>
    RustLib.instance.api.crateApiKeyPublicKeyVerify(public: public, msg: msg, signature: signature);

/// z-base-32 encoding of a public key (pkarr alphabet) - iroh's canonical `to_z32`.
String publicKeyToZ32({required List<int> public}) =>
    RustLib.instance.api.crateApiKeyPublicKeyToZ32(public: public);

/// Parses a public key from its z-base-32 form, returning the 32 raw bytes.
Uint8List publicKeyFromZ32({required String z32}) =>
    RustLib.instance.api.crateApiKeyPublicKeyFromZ32(z32: z32);

/// Lowercase-hex encoding of a public key (iroh's `Display`/`FromStr` form).
String publicKeyToHex({required List<int> public}) =>
    RustLib.instance.api.crateApiKeyPublicKeyToHex(public: public);

/// Parses a public key from lowercase hex, returning the 32 raw bytes.
Uint8List publicKeyFromHex({required String hex}) =>
    RustLib.instance.api.crateApiKeyPublicKeyFromHex(hex: hex);

/// Short, human-readable rendering of a public key (first bytes in hex) - iroh's `fmt_short`.
String publicKeyFmtShort({required List<int> public}) =>
    RustLib.instance.api.crateApiKeyPublicKeyFmtShort(public: public);

/// Parses and canonicalises a relay URL string (validates via `url::Url`), returning the
/// canonical form iroh stores.
String relayUrlParse({required String url}) =>
    RustLib.instance.api.crateApiKeyRelayUrlParse(url: url);

/// Builds an iroh `EndpointAddr` from parts and reads it back through iroh's own accessors -
/// proves construction/accessor fidelity (validates id, relay URLs, and socket addresses).
EndpointAddrParts endpointAddrRoundTrip({required EndpointAddrParts parts}) =>
    RustLib.instance.api.crateApiKeyEndpointAddrRoundTrip(parts: parts);

/// Serialises an `EndpointAddr` to postcard bytes (the canonical iroh wire encoding).
Uint8List endpointAddrEncode({required EndpointAddrParts parts}) =>
    RustLib.instance.api.crateApiKeyEndpointAddrEncode(parts: parts);

/// Deserialises an `EndpointAddr` from postcard bytes back into parts.
EndpointAddrParts endpointAddrDecode({required List<int> bytes}) =>
    RustLib.instance.api.crateApiKeyEndpointAddrDecode(bytes: bytes);

/// Wire-shaped view of an [`EndpointAddr`]: the endpoint id plus its relay URLs and direct IP
/// socket addresses. `Custom` transport addresses are intentionally omitted in v1 (the variant is
/// `#[non_exhaustive]`; we never match it exhaustively).
class EndpointAddrParts {
  final Uint8List id;
  final List<String> relayUrls;
  final List<String> ipAddrs;

  const EndpointAddrParts({required this.id, required this.relayUrls, required this.ipAddrs});

  @override
  int get hashCode => id.hashCode ^ relayUrls.hashCode ^ ipAddrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndpointAddrParts &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          relayUrls == other.relayUrls &&
          ipAddrs == other.ipAddrs;
}
