// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_path_event`

/// Cancels a reactive stream (watchAddr / homeRelayStatus / pathEvents) by its token. Invoked from
/// the Dart subscription's `onCancel` so a cancelled subscription promptly drops the iroh watcher
/// (no leak, no hang).
void cancelStream({required BigInt token}) =>
    RustLib.instance.api.crateApiWatchCancelStream(token: token);

/// A path lifecycle event on a connection, in flat form. `remote_addr` is set for
/// `Opened`/`Closed`/`Selected`; `missed` is set for `Lagged`.
class PathEventInfo {
  final PathEventKind kind;
  final String? remoteAddr;
  final BigInt? missed;

  const PathEventInfo({required this.kind, this.remoteAddr, this.missed});

  @override
  int get hashCode => kind.hashCode ^ remoteAddr.hashCode ^ missed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathEventInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          remoteAddr == other.remoteAddr &&
          missed == other.missed;
}

/// Discriminant for [`PathEventInfo`]. `Unknown` absorbs any future `#[non_exhaustive]` variant.
enum PathEventKind { opened, closed, selected, lagged, unknown }

/// One relay server's connection status (a `homeRelayStatus` update carries a list of these).
class RelayStatusInfo {
  final String url;
  final bool connected;
  final String? lastError;

  const RelayStatusInfo({required this.url, required this.connected, this.lastError});

  @override
  int get hashCode => url.hashCode ^ connected.hashCode ^ lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          connected == other.connected &&
          lastError == other.lastError;
}
