// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'watch.dart';

// These functions are ignored because they are not marked as `pub`: `take`, `wrap`, `wrap`, `wrap`, `wrap`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Connection>>
abstract class Connection implements RustOpaqueInterface {
  /// Accepts the next incoming bidirectional stream from the peer.
  Future<(SendStream, RecvStream)> acceptBi();

  /// Accepts the next incoming unidirectional (receive-only) stream from the peer.
  Future<RecvStream> acceptUni();

  /// The negotiated ALPN protocol for this connection.
  Uint8List alpn();

  /// Closes the connection immediately with an application error code and reason.
  void close({required int errorCode, required List<int> reason});

  /// Waits until the connection is closed and returns the human-readable close reason.
  Future<String> closed();

  /// Opens a new bidirectional stream. Note the lazy-stream footgun: the peer does not observe
  /// the stream until the first write on the returned [`SendStream`].
  Future<(SendStream, RecvStream)> openBi();

  /// Opens a new unidirectional (send-only) stream.
  Future<SendStream> openUni();

  /// Streams path lifecycle events (`Opened`/`Closed`/`Selected`/`Lagged`) for this connection;
  /// the relay-vs-direct transition is observable via `Selected`. `token` lets the Dart
  /// subscription cancel the underlying task via `cancel_stream`.
  Stream<PathEventInfo> pathEvents({required BigInt token});

  /// Receives the next application datagram from the peer.
  Future<Uint8List> readDatagram();

  /// The remote peer's [`EndpointId`](iroh::EndpointId) as 32 raw bytes.
  Uint8List remoteId();

  /// Sends an unreliable, unordered datagram. Errors if too large or unsupported.
  void sendDatagram({required List<int> data});

  /// A process-stable identifier for this connection.
  BigInt stableId();

  /// Connection counters snapshot.
  ConnStats stats();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Incoming>>
abstract class Incoming implements RustOpaqueInterface {
  /// Accepts the connection, completing the handshake and returning a [`Connection`].
  Future<Connection> accept();

  /// Ignores the connection (sends no packet, frees resources).
  void ignore();

  /// Refuses the connection (sends no packet); the peer's connect attempt fails.
  void refuse();

  /// A debug rendering of the remote address that initiated this connection.
  String remoteAddr();

  /// Responds with a retry packet (return-routability / anti-amplification). The peer transparently
  /// reconnects, producing a fresh [`Incoming`].
  void retry();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecvStream>>
abstract class RecvStream implements RustOpaqueInterface {
  /// The QUIC stream id.
  BigInt id();

  /// Reads up to `max_len` bytes. Returns the bytes read, or `None` at end-of-stream.
  Future<Uint8List?> read({required BigInt maxLen});

  /// Reads exactly `len` bytes, erroring if the stream ends early.
  Future<Uint8List> readExact({required BigInt len});

  /// Reads to end of stream, up to `size_limit` bytes.
  Future<Uint8List> readToEnd({required BigInt sizeLimit});

  /// Asks the peer to stop sending on this stream with the given error code.
  Future<void> stop({required int errorCode});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SendStream>>
abstract class SendStream implements RustOpaqueInterface {
  /// Finishes the stream cleanly (signals end-of-data to the peer).
  Future<void> finish();

  /// The QUIC stream id.
  BigInt id();

  /// Resets the stream, abandoning unacknowledged data with the given error code.
  Future<void> reset({required int errorCode});

  /// Writes all of `data` to the stream, applying backpressure as needed.
  Future<void> writeAll({required List<int> data});
}

/// A snapshot of a few useful connection counters.
class ConnStats {
  final BigInt udpTxDatagrams;
  final BigInt udpTxBytes;
  final BigInt udpRxDatagrams;
  final BigInt udpRxBytes;

  const ConnStats({
    required this.udpTxDatagrams,
    required this.udpTxBytes,
    required this.udpRxDatagrams,
    required this.udpRxBytes,
  });

  @override
  int get hashCode =>
      udpTxDatagrams.hashCode ^ udpTxBytes.hashCode ^ udpRxDatagrams.hashCode ^ udpRxBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnStats &&
          runtimeType == other.runtimeType &&
          udpTxDatagrams == other.udpTxDatagrams &&
          udpTxBytes == other.udpTxBytes &&
          udpRxDatagrams == other.udpRxDatagrams &&
          udpRxBytes == other.udpRxBytes;
}
