// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'connection.dart';
import 'key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'watch.dart';

// These functions are ignored because they are not marked as `pub`: `map_relay_mode`

/// Binds a new endpoint. Hides `presets::N0` (DNS/pkarr address lookup + relays + crypto provider);
/// `relay_mode_kind`/`custom_relay_urls` override the relay configuration, `alpns` declares the
/// protocols accepted for inbound connections, and `secret_key` (if given) fixes the identity.
Future<Endpoint> endpointBind({
  Uint8List? secretKey,
  required List<Uint8List> alpns,
  required int relayModeKind,
  required List<String> customRelayUrls,
}) => RustLib.instance.api.crateApiEndpointEndpointBind(
  secretKey: secretKey,
  alpns: alpns,
  relayModeKind: relayModeKind,
  customRelayUrls: customRelayUrls,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Endpoint>>
abstract class Endpoint implements RustOpaqueInterface {
  /// Accepts the next inbound connection, collapsing the lazy `Accept -> Incoming -> Accepting ->
  /// Connection` chain. Resolves to `None` once the endpoint is closed.
  Future<Connection?> accept();

  /// Accepts the next inbound connection as an unaccepted [`Incoming`], letting the caller
  /// inspect the remote address and choose `accept`/`refuse`/`retry`/`ignore`. Resolves to
  /// `None` once the endpoint is closed.
  Future<Incoming?> acceptIncoming();

  /// A snapshot of this endpoint's current address (id + known relay URLs + direct IP addrs).
  EndpointAddrParts addr();

  /// The local socket addresses this endpoint is bound to (`host:port`).
  List<String> boundSockets();

  /// Closes the endpoint gracefully, tearing down connections and background tasks.
  Future<void> close();

  /// Connects to a remote endpoint over the given ALPN protocol, returning an established
  /// [`Connection`]. Mirrors `iroh::Endpoint::connect`.
  Future<Connection> connect({required EndpointAddrParts addr, required List<int> alpn});

  /// Streams the home-relay connection status (one entry per configured relay) as it changes.
  Stream<List<RelayStatusInfo>> homeRelayStatus({required BigInt token});

  /// The endpoint's [`EndpointId`](iroh::EndpointId) (public key) as 32 raw bytes.
  Uint8List id();

  /// Whether the endpoint has been closed.
  bool isClosed();

  /// Replaces the set of accepted ALPN protocols (affects new inbound connections only).
  void setAlpns({required List<Uint8List> alpns});

  /// Streams snapshots of this endpoint's [`EndpointAddr`](iroh::EndpointAddr) as relay/direct
  /// discovery updates it. `token` lets the Dart subscription cancel the underlying task via
  /// `cancel_stream`, which drops the iroh watcher - no leak.
  Stream<EndpointAddrParts> watchAddr({required BigInt token});
}
