// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'connection.dart';
import 'endpoint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartProtocolHandler`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `accept`, `fmt`

/// Starts a [`RouterBuilder`] over `endpoint`.
Future<RouterBuilder> routerBuilder({required Endpoint endpoint}) =>
    RustLib.instance.api.crateApiRouterRouterBuilder(endpoint: endpoint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Router>>
abstract class Router implements RustOpaqueInterface {
  /// Shuts the router down gracefully, stopping its accept loop.
  Future<void> shutdown();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RouterBuilder>>
abstract class RouterBuilder implements RustOpaqueInterface {
  /// Registers `on_accept` as the handler for connections negotiating `alpn`. The Dart callback
  /// receives each accepted [`Connection`] and resolves when it has finished handling it (after
  /// which the connection is dropped unless other clones are held).
  Future<void> accept({
    required List<int> alpn,
    required FutureOr<void> Function(Connection) onAccept,
  });

  /// Spawns the router's accept loop and returns the running [`Router`].
  Future<Router> spawn();
}
