// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the ABI version compiled into this native library.
///
/// Also serves as a minimal end-to-end check that the FFI path works:
/// Rust -> FRB glue -> native lib -> Dart loader -> Dart call.
int irohdartAbiVersion() => RustLib.instance.api.crateApiSimpleIrohdartAbiVersion();

/// Returns the `iroh` crate version this wrapper was built against, for diagnostics.
String irohdartIrohVersion() => RustLib.instance.api.crateApiSimpleIrohdartIrohVersion();
